spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/glot_prod?validationQuery="select 1"&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: operator
    password: operator
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-test-query: select 1 from dual
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        enable_lazy_load_no_trans: true
        format_sql: true
        hbm2ddl:
          auto: validate
    defer-datasource-initialization: false
    show-sql: true
  mail:
    host: smtp.gmail.com # SMTP 서버 호스트
    port: 587 # SMTP 서버 포트
    username: hansol8701 # SMTP 서버 로그인 아이디 (발신자)
    password: ytbdvpfawwymfcvr    # SMTP 서버 로그인 패스워드 (앱 비밀번호)
    properties:
      mail:
        smtp:
          auth: true # 사용자 인증 시도 여부 (기본값 : false)
          timeout: 5000 # Socket Read Timeout 시간(ms) (기본값 : 무한대)
          starttls:
            enable: true # StartTLS 활성화 여부 (기본값 : false)
  flyway:
    url: jdbc:mariadb://localhost:3306/glot_prod?validationQuery="select 1"&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC&useLegacyDatetimeCode=false
    user: operator
    password: operator
    baseline-on-migrate: true
    enabled: true
api:
  port-one:
    imp-key: 8013673665434435
    imp-secret: 0EQjdQ5sbOSRNgO2p1yJfZvSAs2TXgLgkS4cXHieklkfk1olWCGHczP4GaOGfXJfXz1mqpZtqCa5QmoN
  cool-sms:
    api-key: NCSAKNHPLFIWORZK
    secret-key: UZRADMPIGSFTZ8HZAMHAPWPKDEHKBOW6
    from-mobile: 01029577501